### ISSUE TITLE
ModuleNotFoundError: No module named 'SVASTIN'z

### ISSUE THREAD

**Issue by Au-LiuJY** [Brittany-Chen/SVASTIN#2]
When I run **python attack.py**,some errors occur:
/SVASTIN/model/model.py", line 4, in <module>
    import SVASTIN.config as c
ModuleNotFoundError: No module named 'SVASTIN'

I see the model.py:
```
import SVASTIN.config as c
from SVASTIN.model.hinet import Hinet_stage
```
it seems like it use absolute import?

Later,I try to Run in the project root directory,and do **python -m SVASTIN.attack**.
But in this way, I need to modify so many relevant .py files.I think it won't be sensible.

I'm more than delighted to see your timely answer.Thanks in advance!

**Comment by colourful-pan** [comment]
First of all thank you very much for your question.
Our code is written under windows, suitable for windows system, and the root directory of our code "SVASTIN" needs to be placed in the directory of the mmaction framework to run normally.

**Comment by Au-LiuJY** [comment]
> First of all thank you very much for your question. Our code is written under windows, suitable for windows system, and the root directory of our code "SVASTIN" needs to be placed in the directory of the mmaction framework to run normally.

OK,I think I should reorganize the structure of these files.Thank you for your timely answer!

**Comment by Au-LiuJY** [comment]
I'm sorry that I have other problems when I try to reproduce your work.
The problem now is that how you make your 'config'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mmaction2/mmaction/SVASTIN/attack.py", line 21, in <module>
    model = init_recognizer(args.config_file, args.checkpoint_file, device=device)  # or device='cuda:0'
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mmaction/apis/inference.py", line 93, in init_recognizer
    config = mmengine.Config.fromfile(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
                                        ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/mmengine/config/config.py", line 856, in _file2dict
    check_file_exist(filename)
  File "/lib/python3.11/site-packages/mmengine/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/mmaction2/mmaction" does not exist



Later I see your 'args.py', its content is:
import argparse

def get_args_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--workers', type=int, help='number of data loading workers', default=0)
    parser.add_argument('--dataset', type=str, help='The dataset that was attacked, UCF101 or Kinetic400', default="UCF101")
    parser.add_argument('--config_file', type=str, help='Model configuration file',
                        default='')
    I want to know how to set these parameters，**specially the'config_file'and the 'checkpoint_file'**.The inputpath I think I should  place the pictures(frames) of the videos of UCF101.Is it right?
     Hoping to see your answer!Thanks in advance!

**Comment by colourful-pan** [comment]
Our code leverages the mmaction framework, utilizing a pre-trained model provided within it. The 'config_file' refers to the configuration file associated with the model, while the 'checkpoint_file' denotes the location of the pre-trained model. The 'inputpath' specifies the directory containing the test dataset, such as 'Kinetics-400/videos_val'.

**Comment by payphone131** [comment]
> Traceback (most recent call last):

Hi, I am also facing the same problem. Have you solved it yet?

**Comment by payphone131** [comment]
> I'm sorry that I have other problems when I try to reproduce your work. The problem now is that how you make your 'config'.
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "/mmaction2/mmaction/SVASTIN/attack.py", line 21, in model = init_recognizer(args.config_file, args.checkpoint_file, device=device) # or device='cuda:0' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/mmaction/apis/inference.py", line 93, in init_recognizer config = mmengine.Config.fromfile(config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/mmengine/config/config.py", line 461, in fromfile cfg_dict, cfg_text, env_variables = Config._file2dict( ^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/mmengine/config/config.py", line 856, in _file2dict check_file_exist(filename) File "/lib/python3.11/site-packages/mmengine/utils/path.py", line 23, in check_file_exist raise FileNotFoundError(msg_tmpl.format(filename)) FileNotFoundError: file "/mmaction2/mmaction" does not exist
> 
> Later I see your 'args.py', its content is: import argparse
> 
> def get_args_parser(): parser = argparse.ArgumentParser() parser.add_argument('--workers', type=int, help='number of data loading workers', default=0) parser.add_argument('--dataset', type=str, help='The dataset that was attacked, UCF101 or Kinetic400', default="UCF101") parser.add_argument('--config_file', type=str, help='Model configuration file', default='') I want to know how to set these parameters，**specially the'config_file'and the 'checkpoint_file'**.The inputpath I think I should place the pictures(frames) of the videos of UCF101.Is it right? Hoping to see your answer!Thanks in advance!

Hi, I am also facing the same problem. Have you solved it yet?

**Comment by colourful-pan** [comment]
I am very honored that you are interested in my code!
Our code is based on [mmaction2](https://mmaction2.readthedocs.io/en/latest/index.html ) Built with a framework, so you can find "config_file" and its corresponding "checkpoint_file" in mmaction2. For the models on the UCF-101 dataset, you can download them directly through the [GoogleDrive](https://drive.google.com/file/d/1nlaIvaQN6vmegId3UX3XjrPdSt6Nt82I/view?usp=drive_link).
